---
- hosts: all
  become: yes
  roles:
    - common
    - firewall

- hosts: dbservers
  become: yes
  roles:
    - geerlingguy.mysql

- hosts: webservers
  become: yes
  roles:
    - webserver
    - laravel
