---
- name: Install SELinux Python Software
  dnf:
    name:
      - python3-libsemanage
      - policycoreutils-python-utils

- name: Allow Web Services Network Access
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Add Default SELinux Context
  sefcontext:
    target: /srv/http(/.*)?
    setype: httpd_sys_content_t
  notify: restorecon

- name: Add Custom SELinux Context
  sefcontext:
    target: "{{ item }}"
    setype: httpd_sys_rw_content_t
  loop: "{{ webserver_writeable_files }}"
  notify: restorecon
